#!/bin/bash

set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

setup_war_file() {
    if [[ ! -d "${SELDON_SERVER_HOME}/server/target" ]]; then
        (cd ${SELDON_SERVER_HOME}/server && mvn package -DskipTests -q)
    fi

    WARFILE_PATH=$(ls ${SELDON_SERVER_HOME}/server/target/seldon-server-*.war)
    WARFILE=$(basename ${WARFILE_PATH})
    WARFILE_VERSION=$(echo ${WARFILE}|sed -e 's/seldon-server-//' -e 's/.war$//')

    #echo "WARFILE_PATH[${WARFILE_PATH}]"
    #echo "WARFILE[${WARFILE}]"
    #echo "WARFILE_VERSION[${WARFILE_VERSION}]"
}

extract_war_file() {
    mkdir -p ${WEBAPPS_DIR}/ROOT
    unzip -qx -d ${WEBAPPS_DIR}/ROOT/ ${WARFILE_PATH} &> /dev/null
}

echo "-- setting up webapps for seldon api --"

SELDON_SERVER_HOME=${STARTUP_DIR}/../../seldon-server
LOCAL_DATA_DIR=${STARTUP_DIR}/../local_data
WEBAPPS_DIR=${LOCAL_DATA_DIR}/webapps

setup_war_file
extract_war_file

