#!/bin/bash

set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"
LOCAL_DATA_DIR=${STARTUP_DIR}/../local_data

WEBAPPS_DIR=${LOCAL_DATA_DIR}/webapps
echo "removing ${WEBAPPS_DIR})" && rm -rf ${WEBAPPS_DIR}

(cd ${STARTUP_DIR} && make webapps)

copy_dir_webapps() {
    local DIR_NAME=$1
    TGT_DIR=${TOMCAT_HOME}/webapps/${DIR_NAME}
    if [[ -d ${TGT_DIR} ]];then
        echo "Removing ${TGT_DIR}" && rm -rf ${TGT_DIR}
    fi
    echo "Copying ${DIR_NAME}" && cp -R ${STARTUP_DIR}/webapps/${DIR_NAME} ${TOMCAT_HOME}/webapps
}

copy_dir_webapps api-spec
copy_dir_webapps swagger
copy_dir_webapps movie-demo

