#!/bin/bash

set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"

create_models() {
    ${STARTUP_DIR}/create_models.sh movielens matrix_factorization
    ${STARTUP_DIR}/create_models.sh movielens item_similarity
    ${STARTUP_DIR}/create_models.sh movielens semantic_vectors
    ${STARTUP_DIR}/create_models.sh movielens word2vec
}

activate_models() {
    ${STARTUP_DIR}/activate_models.sh movielens matrix_factorization
    ${STARTUP_DIR}/activate_models.sh movielens item_similarity
    ${STARTUP_DIR}/activate_models.sh movielens semantic_vectors
    ${STARTUP_DIR}/activate_models.sh movielens word2vec
}

create_models
activate_models

