#!/bin/bash

set -o nounset
set -o errexit

STARTUP_DIR="$( cd "$( dirname "$0" )" && pwd )"
echo "${STARTUP_DIR}"

SELDON_SERVER_HOME=${STARTUP_DIR}/../../seldon-server
SELDON_SPARK_HOME=${SELDON_SERVER_HOME}/offline-jobs/spark
CLIENT=movielens
export DB_HOST=127.0.0.1
if [[ "$(uname)" == "Darwin" ]]; then
    BOOT2DOCKER_HOST=$(boot2docker ip)
    export DB_HOST=$BOOT2DOCKER_HOST
fi
DB_USER=root
DB_PASS=mypass
DAY=1

SELDON_MODELS_DIR=~/seldon-models

cat ${SELDON_MODELS_DIR}/${CLIENT}/item-similarity/${DAY}/part* | ${SELDON_SPARK_HOME}/scripts/item-similarity/create-sql.py > ${STARTUP_DIR}/upload.sql

echo "-- uploading sql --"
mysql -h${DB_HOST} -u${DB_USER} -p${DB_PASS} ${CLIENT} < ${STARTUP_DIR}/upload.sql

